### PR TITLE
DKAN upgrade to 7.x-1.13.6

### PR DESCRIPTION
**Pull request by msolv**
## Description

DKAN Upgrade to 7.x-1.13.6

## QA Process

- [ ] Tests should pass.

### CODE REVIEW

**Comment by dkinzer** [comment]
@msolv @janette I'm worried there is something wrong with this PR... it should not be 15 commits behind master: https://github.com/NuCivic/dkan_starter/tree/1.13.6.0

**Comment by msolv** [comment]
@dkinzer yes, I've updated the branch and I'm running remake again. I'll push as soon as it finishes.

**Comment by dkinzer** [comment]
@msolv @janette, the only difference between these two branches at this point should be timestamps: 

https://github.com/NuCivic/dkan_starter/compare/1.13.6.0...rc-1.13.6.0.0

But that is not what I am seeing.

**Comment by msolv** [comment]
@dkinzer did you see my comment? I'm going to push an update soon.

**Comment by dkinzer** [comment]
@msolv yes, I just put that link there so that there is a frame of reference to check.  I'm still seeing odd differences.  Are you running `ahoy build remake`?

**Comment by msolv** [comment]
@dkinzer Yes, I'm running `ahoy build remake`

The branch is 3 commits ahead of master now: https://github.com/NuCivic/dkan_starter/compare/1.13.6.0

**Comment by dkinzer** [comment]
Also I don't know what this is `ahoy/site/.cache/36/3674690d5e19e1d8d05b6039946e83542eb483bc7196a4097da1c7ddb6227dcc.php`?

**Comment by msolv** [comment]
@dkinzer Me neither. It was generated by `ahoy build remake`

**Comment by dkinzer** [comment]
@msolv ok, it all looks good now.

**Comment by msolv** [comment]
@dkinzer Ok, awesome. Will merge as soon as tests pass.

**Pull request merged**
