### PR TITLE
[CIVIC-6270] Clean up all CircleCI specific settings in settings.php

### PR DESCRIPTION
**Pull request by rhabbachi**
Issue: CIVIC-6270

## Description
In settings.php we are setting some configuration only for CircleCI. This was necessary to have the required environment to pass tests on the various client sites. Unfortunately this make reproducing failed tests locally for debugging much harder.

## Acceptance Criteria
1. Clean-up all unneeded CI specific settings from the {{settings.php}}.
2. Export environment needed for tests to Behat before/after scenarios tags.

## Test Updates
No new tests are to be added. The current tests should still pass.

## Documentation Updates
None needed.

### CODE REVIEW

**Comment by dkinzer** [comment]
@rhabbachi issue with this is that some sites have workflow enabled and without doing a little CI juggling, some tests for workflow sites will fail.

**Comment by rhabbachi** [comment]
@dkinzer I thought that juggling should be taken care of with the `@enable_DkanWorkflow` tag in behat.

**Comment by dkinzer** [comment]
@rhabbachi but he issue is that for sites that have it enabled already dkan tests fail because the dkan test suites assume workflow is not enabled until it gets tested.

**Comment by rhabbachi** [comment]
@dkinzer I see. I can't see any easy way to clean the conditional `dkan_workflow` from the settings file unless we do a costly dkan tests refactor.

Thanks for pointing that out @dkinzer! Can you please restore the juggling?

**Comment by dkinzer** [comment]
sure thing

**Comment by dkinzer** [comment]
@rhabbachi the other issue is that i think if `$conf['cron_safe_threshold'] = 0;` is set, then cron jobs will not run in production.  That's OK in CI to prevent certain weirdness but not good in a production site.

**Comment by rhabbachi** [comment]
@dkinzer I was under the impression that setting `cron_safe_threshold` will disable the automated Drupal Cron on page load. Since we are triggering cron from Drush via Jenkins jobs and not relaying on the built in automation that looked fine for me. Is my assumption flawed?

**Comment by dkinzer** [comment]
@rhabbachi oh, you are correct.  My bad.

**Comment by dafeder** [comment]
This seems like it should be handled in DKAN, not DKAN Starter. Let's revisit and try that.

**Comment by dafeder** [comment]
This should only be merged once NuCivic/dkan#1976 passes and is merged.

**Comment by dkinzer** [comment]
@dafeder Nucivic/dkan#1976 is passing again.

**Pull request merged**
